/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_jnitest_jni_JniTest */
#include "jni.h"

#ifndef _Included_com_jnitest_jni_JniTest
#define _Included_com_jnitest_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jnitest_jni_JniTest_testVoid
  (JNIEnv *, jobject);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnitest_jni_JniTest_testBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_jnitest_jni_JniTest_testChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_jnitest_jni_JniTest_testByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_jnitest_jni_JniTest_testShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jnitest_jni_JniTest_testInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jnitest_jni_JniTest_testLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_jnitest_jni_JniTest_testFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_jnitest_jni_JniTest_testDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnitest_jni_JniTest_testString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testByteArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jnitest_jni_JniTest_testByteArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testMixed
 * Signature: ([BZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnitest_jni_JniTest_testMixed
  (JNIEnv *, jobject, jbyteArray, jboolean, jstring);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testOnCalledOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jnitest_jni_JniTest_testOnCalledOne
  (JNIEnv *, jobject);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testOnCalledTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jnitest_jni_JniTest_testOnCalledTwo
  (JNIEnv *, jobject);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testByteArrayReference1
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jnitest_jni_JniTest_testByteArrayReference1
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jnitest_jni_JniTest
 * Method:    testByteArrayReference2
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jnitest_jni_JniTest_testByteArrayReference2
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
